title: An Early late site
description: Starting with Dayatech
theme: just-the-docs

url: https://pinatalewis.github.io

aux_links:
  Template Repository: https://github.com/pinatalewis/pinatalewis.github.io
